### PR TITLE
March2016

### PR DESCRIPTION
**Pull request by RaphaelRaphael**
After performing different tests, the package is ok when I test it in Rstudio and passing the Bioconductor filters from BiocCheck 
Maybe travis is not configure in the same way I think we should desactivate travis !

### CODE REVIEW

**Comment by sahirbhatnagar** [comment]
Where are you testing the package? When you say " ok when I test it in Rstudio", are you referring to your desktop? HYDRA? You need to test the package on a different system than the one it was  built on because they're files present on your local installation which would not be present on someone else's computer (for example see @turgeonmaxime most recent comment regarding the missing .Rda file). This is the advantage of having travis enabled. It is being tested on a system which is independent of the one on which the package was built.

There are issues with the vignette: You cannot source code with an [absolute path](https://github.com/GreenwoodLab/funtooNorm/blob/master/vignettes/funtooNorm.Rnw#L106). The data being loaded is [not found](https://github.com/GreenwoodLab/funtooNorm/blob/master/vignettes/funtooNorm.Rnw#L108)

**Comment by turgeonmaxime** [comment]
Thanks for updating the `NAMESPACE` and the vignette. But Sahir's main comment still holds: what do you mean when you write "after performing different tests, the package is ok"? I've downloaded your version of the repository and ran the usual R checks (`R CMD check`; there's also a button in RStudio that does the same thing), and I get an error:

``` r
> mySampleSet=fromRGChannelSet(RGsetEx)
Error in fromRGChannelSet(RGsetEx) : 
  Your object should contain a field "cell_type" in it's phenotype
         data minfi::pData(rgset) in order to use funtooNorm
Execution halted
```

Incidentally, this is the same error that is reported by Travis (look at the log file). There is no way BioConductor will accept the package if this is not fixed. There are also some issues with the documentation -- again, this is all spelled out in the Travis log file, or the log file you get from running `R CMD check` on your computer.

**Comment by turgeonmaxime** [comment]
By the way, I tracked down the error: it comes from the documentation. One of the requirements of `R CMD check` is that all examples appearing in the documentation should be able to run. To check that, you can also use

``` r
devtools::run_examples()
```

If you really want to keep your example `mySampleSet=fromRGChannelSet(RGsetEx)` in the documentation, you either have to create a valid `RGsetEx` at the same time, or make sure the example is not run during the check (which you can do by using `\dontrun{}`; see [this](http://r-pkgs.had.co.nz/man.html#man-functions)). But of course, you can also remove it altogether.

**Comment by RaphaelRaphael** [comment]
Ok I get it
The first merge I was assuming an automatic git add for all the modified documents, thats why NAMESPACE and co where not updated
I also assume check to be run behind biocCheck, now I have all the infos to make it run !

**Comment by turgeonmaxime** [comment]
@RaphaelRaphael You should know that, by default, Travis treats warnings as errors. So if you can get rid of all the real errors, it should be good enough (even though travis may still fail).

**Comment by RaphaelRaphael** [comment]
I should merge march2016 in a few minutes I just have a few warnings. 
Thanks a lot Maxime for your help

**Pull request merged**
